server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Sawan@7sawan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
